export const MAX_FAILED_LOGIN_ATTEMPTS = 5;
export const LOCKOUT_DURATION_MINUTES = 30;
export const FAILED_ATTEMPT_RESET_WINDOW_HOURS = 1;

export const EMAIL_VERIFICATION_EXPIRY_HOURS = 24;
export const EMAIL_VERIFICATION_RESEND_COOLDOWN_MINUTES = 5;
